### ISSUE TITLE
Import the generated mask through openslide-python and got a whole-black image

### ISSUE THREAD

**Issue by Kayshine** [computationalpathologygroup/ASAP#143]
Hi, I have input a WSI into ASAP and got the mask using multireslotionimageinterface and saved as TIF document. But when I used python to load the mask and got a thumbnail of it which showed **all black** and obviously was wrong.
If there is a problem that the multireslotionimageinterface saves the mask wrong?
The generated mask opened in ASAP:
![2019-04-04 20-07-27屏幕截图](https://user-images.githubusercontent.com/42996550/55573914-bdc5f700-573d-11e9-89ea-d9eadbe481ab.png)
The generated mask opened through openslide-python:
![1](https://user-images.githubusercontent.com/42996550/55574005-e8b04b00-573d-11e9-9d4c-bc4db3201413.jpg)

**Comment by GeertLitjens** [comment]
Hi, this is not an issue with ASAP. Openslide does in principle not support non-RGB TIFFs, so I don't know what it will output. You could use the Python wrapping around the MultiResolutionImageInterface to read the file in Python. You need to add the bin directory of ASAP to your Python path. You can find usage examples here https://academic.oup.com/gigascience/article/7/6/giy065/5026175

**Comment by GeorgeBatch** [comment]
**Opening with ASAP/mir works.**
![Screenshot from 2024-03-01 16-07-58](https://github.com/computationalpathologygroup/ASAP/assets/46561186/6f518471-adf8-40a9-8634-a4ce89b7231d)

**Opening with OpenSlide also works.** For openslide, the the read-region gets a 4-channel mask. The 4th channel is completely white (all values are 255). Any displaying any other channel will get you a binary mask with 0 and 1 values. You might want to save it with 255 instead of 1 to get the black-and-white (png) image.

![Screenshot from 2024-03-01 16-04-17](https://github.com/computationalpathologygroup/ASAP/assets/46561186/5069e898-ac7e-4739-94a0-ba90b855bf03)
