### ISSUE TITLE
Tiff file display weird

### ISSUE THREAD

**Issue by RunnerRenke** [computationalpathologygroup/ASAP#223]
When I open the tiff file with ASAP, there are a lot of black areas on the view; I look at the source code and find that the tiff-format image is read by default from TIFFImageFactory; there seems to be something wrong with TIFFImage's readdDataFromImage method; But when I adjusted the read priority of openslide, I found that the tiff file could be displayed normally；So Is thera a bug in TIFFImage class？
Here is image:
![image](https://user-images.githubusercontent.com/94215472/141609670-2aad0f9d-fa4f-41c6-b074-70b15593d53b.png)

By the way, I have some tiff files, but I can't get the associated images by openslide_get_associated_image_names methon，but the Aperio ImageScope can open these svs files  and display the associated images normal. So what should I do to get the associated image of the tiff file?

Associated images display normal in Aperio ImageScope;
![image](https://user-images.githubusercontent.com/94215472/141609833-133e9c59-bc8b-4226-b3cd-bfa8f762e898.png)

**Comment by RunnerRenke** [comment]
![image](https://user-images.githubusercontent.com/94215472/141609652-24804796-d2c2-4cd5-a557-41aee9ee50d3.png)

**Comment by GeertLitjens** [comment]
It depends a lot where your TIFF file comes from, for example, Philips TIFF and Aperio TIFF are distinctly different. We prefer to try to use the generic TIFFImage reader because it is much faster than OpenSlide, but it does only support straightforward TIFF without any associated images. So in your case, I would simply specify the factory that is used to read the slide manually. We don't offer support for reading associated images at the moment, so I cannot help you with that
